FROM bellsoft/alpaquita-linux-base:stream-glibc

ARG UID=1001
RUN adduser -S gretljobstarter -u $UID

ENV HOME=/app
WORKDIR $HOME

COPY build/native/nativeCompile/jobstarter ./application

RUN chown $UID:0 . && \
    chmod 0775 . && \
    ls -la

USER $UID
EXPOSE 8080

CMD ["./application"]